# Generated by Django 5.0.7 on 2024-07-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_paymentmethod1_delete_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(1, 'QR'), (2, 'CREDIT')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethod1',
        ),
    ]
