# Generated by Django 5.0.7 on 2024-07-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_paymentmethod_delete_paymentmethod1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.payment'),
        ),
    ]
