# Generated by Django 5.0.7 on 2024-07-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_paymentitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentitem',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='payment',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PaymentItem',
        ),
    ]
