# Generated by Django 5.0.7 on 2024-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cart_customer_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItem',
            field=models.ManyToManyField(null=True, through='shop.CartItem', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderItem',
            field=models.ManyToManyField(null=True, through='shop.OrderItem', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(null=True, to='shop.productcategory'),
        ),
    ]
